name: CI/CD to AWS ECR and ECS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS credentials (hardcoded)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: access
        aws-secret-access-key: secret
        aws-region: ap-south-1

    # 3️⃣ Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t 443370696974.dkr.ecr.ap-south-1.amazonaws.com/my-first-repo:$IMAGE_TAG .

    # 5️⃣ Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push 443370696974.dkr.ecr.ap-south-1.amazonaws.com/my-first-repo:$IMAGE_TAG

    # 6️⃣ (Optional) Deploy to ECS — You can enable this if you configure ECS
    # - name: Deploy to ECS
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    #   with:
    #     task-definition: ecs-task-definition.json
    #     service: my-ecs-service
    #     cluster: my-ecs-cluster
    #     wait-for-service-stability: true
    #     image: |
    #       my-container-name=443370696974.dkr.ecr.ap-south-1.amazonaws.com/my-first-repo:${{ github.sha }}
